services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.e2e
    environment:
      # Override specific values or add runtime-specific variables
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./test_data:/app/test_data
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - masterspeak-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.e2e
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - masterspeak-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - masterspeak-network

  e2e-tests:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    volumes:
      - ./e2e:/app
      - ./e2e/test-results:/app/test-results
      - ./e2e/playwright-report:/app/playwright-report
    env_file:
      - .env.e2e
    depends_on:
      - frontend
      - backend
    networks:
      - masterspeak-network
    command: ["npx", "playwright", "test", "--reporter=html,json"]

volumes:
  redis_data:

networks:
  masterspeak-network:
    driver: bridge