# fly.toml - Fly.io Configuration for MasterSpeak AI Backend

app = "masterspeak-ai"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "backend/Dockerfile"

[env]
  ENV = "production"
  DEBUG = "false"
  RATE_LIMIT_ENABLED = "true"
  RATE_LIMIT_DEFAULT = "60/minute"
  RATE_LIMIT_AUTH = "5/minute"
  RATE_LIMIT_ANALYSIS = "10/minute"
  RATE_LIMIT_UPLOAD = "5/minute"
  RATE_LIMIT_HEALTH = "100/minute"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "1s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

    [services.http_checks.headers]
      User-Agent = "fly-health-check"

[[vm]]
  size = "shared-cpu-1x"
  memory = 512

[deploy]
  release_command = "python -c 'print(\"Database migration placeholder - implement Alembic here if needed\")'"

[metrics]
  port = 8000
  path = "/metrics"